site_name: AV
site_url: https://asvarga.github.io/
# repo_url: https://github.com/asvarga/asvarga.github.io
plugins:
  # - awesome-pages
  - ezlinks
  - search
  - tags:
      tags_file: wiki/index.md
  - blog
  - offline
  - redirects:
      redirect_maps:
        's/forge/index.md': 'https://cs.brown.edu/media/filer_public/e7/ae/e7aee136-a292-4b44-8e3f-7841aad57475/vargaalexander.pdf'
        's/forge-paper/index.md': 'https://cs.brown.edu/~sk/Publications/Papers/Published/ngp----forge/'
  - social
  # - macros
theme:
  favicon: files/triangle-wave.svg
  icon:
    logo: material/triangle-wave
    repo: fontawesome/brands/github
    # tag: 
    #   default: fontawesome/solid/frog
  name: material
  custom_dir: docs/overrides
  palette:
    - scheme: slate
      primary: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: deep orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
  features:
    - content.code.copy
    - content.code.select
    - navigation.indexes
    # - navigation.instant  # bug: requires manual page reload for equations to render
    # - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
extra:
  # tags: 
  #   Ordinal: Ordinal
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/alexander-varga/
    - icon: fontawesome/brands/github 
      link: https://github.com/asvarga
    - icon: fontawesome/brands/stack-overflow 
      link: https://www.stackoverflow.com/users/1684606/alex-varga
    - icon: fontawesome/brands/youtube 
      link: https://www.youtube.com/user/avarga93/videos
    - icon: fontawesome/brands/flickr 
      link: https://www.flickr.com/photos/124356640@N03
    - icon: fontawesome/brands/vimeo 
      link: https://www.vimeo.com/user99108597
markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  # - wikilinks
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tilde
  # - pymdownx.emoji:
  #    emoji_index: !!python/name:material.extensions.emoji.twemoji 
  #    emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra_javascript:
  - javascripts/katex.js 
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  - stylesheets/extra.css
