site_name: AV
plugins:
  - ezlinks
  - search
  - tags
theme:
  favicon: Files/triangle-wave-icon.png
  icon:
    logo: material/triangle-wave
  name: material
  palette:
    - scheme: slate
      primary: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: deep orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
