site_name: AV
plugins:
  - ezlinks
  - search
  - tags
theme:
  name: material
  # palette:
  #   scheme: slate
  #   primary: deep orange
      # Palette toggle for light mode
  palette:
    - scheme: slate
      primary: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: deep orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
